src:
  dir: /Users/Rodion.Khvorostov/Desktop/Data/LanguageStudyData
  files:
    - name: EnglishToRussian.txt
      deckLabel: en
      src: en
      dest: ru
      translator: yandex
    - name: RussianToEnglish.txt
      deckLabel: en
      src: ru
      dest: en
      translator: yandex
    - name: GermanToEnglish.txt
      deckLabel: de
      src: de
      dest: en
      translator: deepl
    - name: EnglishToGerman.txt
      deckLabel: de
      src: en
      dest: de
      translator: deepl
    # - name: TestYandex.txt
    #   deckLabel: test
    #   src: en
    #   dest: ru
    #   translator: yandex
    # - name: TestDeepl.txt
    #   deckLabel: test
    #   src: en
    #   dest: de
    #   translator: deepl


deckLabels:
  en: English
  de: German
  ru: Russian
  test: Test